---
name: Rémi
surname: Thériault
profilepic: "img/profile.png"
position: "Postdoctoral Fellow"
qualifications: "PhD"
address: "New York University, New York, USA"
phone: (332) 400-6781
www: remi-theriault.com
email: "remi.theriault@nyu.edu"
twitter: RemiTPsyc
github: rempsyc
# linkedin: rempsyc

aboutme: |
  \RaggedRight My training and interests lie at the intersection of social psychology, neuroscience, and positive psychology. Over the past decade, my research has focused on developing and testing innovative psychological interventions to positively transform our relationships to others and the world. In my postdoctoral research, I attempt to reduce affective polarization by appealing to shared social identities. I am also passionate about open science, reproducible science, metascience, and data science using R (this CV was [made in R](https://github.com/rempsyc/cv)).

date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "333333" # my shirt on the profil pic is 839AC4, but we take a bit lighter for better look (6FA3CE)
# Ok recent feedback was to not use colour at all here, so instead we go with the dark blue of my suit
# (21242D) so it doesn't even look that obvious but we still have a little something.
# #333333 is the default grey.
urlcolor: blue
linkcolor: blue
output: 
  vitae::awesomecv:
    page_total: true
header-includes:
  - \usepackage[gen]{eurosym}
papersize: letter
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#######################
#### SHORT VERSION ####
#######################

# Whether to print a shortened version of the CV
short <- FALSE

########################
#### PACKAGE SETUP #####
########################

# Required packages
library(vitae)
library(dplyr)

# For Google scholar data/visualization
library(scholar)
library(patchwork)
library(see)
library(rsvg)
library(kableExtra)
library(tidyverse)

language <- "EN" # If not EN, will choose the alternative names in the data
# So far only for nice_awards() and nice_grants()

# To format links throughout the CV
source("files/functions.R")

# Some feedback we got was to increase font size to at least 12 pt everywhere
# But this has proven to be much more complex than anticipated...
# Increases font sizes
# (e.g., 1.1 = 10% increase; 0.90, 10% decrease)
# First delete awesome-cv.cls if it was already modified with the function below
# Otherwise no need to delete it.
# file.remove("awesome-cv.cls")
# Then knit once (ctrl+K) to recreate the .cls file):
# Then run:
# scale_awesomecv_fonts(scale = 1.1)

# Automatically bold your name in the publication section
author_bold <- "Thériault, R."

########################
#### GOOGLE SCHOLAR ####
########################

# Specify your Google scholar profile
scholar.profile <- "NrfwEncAAAAJ" # Get it from your Google Scholar profile URL

# Specify your Google scholar short author name
author.name <- "rém thériault"
# Note: correct name may vary (e.g., if you inconsistently used middle name initials)
# Dominique Makowski's was simply "d makowski", so the pattern is unclear 
# But usually it seems 1-3 letters from first name plus full last name

# When in doubt, the correct author name can be obtained through:
# get_scholar_name(scholar.profile) # (after defining 'scholar.profile' above)

# Name inconsistencies should be corrected manually in file 'files/make_data_impact.R' (lines 14-16).

headcolor <- "0a0a0a"

########################
##### INSTRUCTIONS #####
########################

# Change the order of sections below as desired.
# Edit the individual files ("childs") to edit the content as desired.
# Add `eval = !short` to code chunks to make them optional for the short version

# See all instructions and tips here: https://github.com/rempsyc/cv

```

```{r Education parent, child=c('sections/education.Rmd')}
```

```{r Publications parent, child=c('sections/publications.Rmd')}
```

```{r Preprints parent, child=c('sections/preprints.Rmd'), eval = !short}
```

\setlength{\parskip}{8pt}

```{r Grants parent, child=c('sections/grant.Rmd'), eval=T}
```

\pagebreak

```{r Awards parent, child=c('sections/awards.Rmd')}
```

```{r Teaching parent, child=c('sections/teaching.Rmd')}
```

```{r Invited talks parent, child=c('sections/invited_talks.Rmd'), eval = !short}
```

```{r Conference talks parent, child=c('sections/conference_talks.Rmd'), eval = !short}
```

```{r Conference posters parent, child=c('sections/conference_posters.Rmd'), eval = !short}
```

```{r Software parent, child=c('sections/software.Rmd')}
```

```{r Academic service parent, child=c('sections/service.Rmd'), eval = !short}
```

```{r Blogs parent, child=c('sections/blogs.Rmd'), eval = T}
```

```{r Media coverage parent, child=c('sections/media_coverage.Rmd'), eval = T}
```

```{r References parent, child=c('sections/references.Rmd'), eval = !short}
```

<!-- We skip the sections below for now. They are on the website and it was recommended to avoid them for the CV for applying to prof positions -->

```{r Other experience parent, child=c('sections/other_experience.Rmd'), eval = F}
```

```{r Leadership parent, child=c('sections/leadership.Rmd'), eval = F}
```

```{r Varia parent, child=c('sections/varia.Rmd'), eval = F}
```

```{r credit parent, child=c('sections/credit.Rmd'), eval = F}
```
