---
name: Rémi
surname: Thériault
profilepic: "img/profile.png"
position: "Chercheur postdoctoral"
qualifications: "PhD"
address: "New York University, New York, USA"
phone: (332) 400-6781
www: remi-theriault.com/fr
email: "remi.theriault@nyu.edu"
linkedin: rempsyc
orcid: "0000-0003-4315-6788"
# googlescholar: NrfwEncAAAAJ
# github: rempsyc
# twitter: RemiTPsyc
# pronouns: "il/lui"

aboutme: |
  \RaggedRight Mes intérêts se situent à l’intersection de la psychologie sociale, des neurosciences et de la psychologie positive, et mes recherches se penchent sur le bien-être optimal, la cohésion sociale, et notre rapport à l’environnement. Dans mes recherches postdoctorales, je tente de réduire la polarisation politique via le développement d'identités sociales partagées. Je suis également passionné par la science ouverte, la science reproductible, la métascience et la science des données à l’aide de R (ce CV a aussi été [réalisé en R](https://github.com/rempsyc/cv)).

headcolor: "6FA3CE" # my shirt on the profil pic is 839AC4, but we take a bit lighter for better look (6FA3CE)
# Ok recent feedback was to not use colour at all here, so instead we go with the dark blue of my suit
# (21242D) so it doesn't even look that obvious but we still have a little something.
# #333333 is the default grey.
urlcolor: blue
linkcolor: blue
output: 
  vitae::awesomecv:
    page_total: true
header-includes:
  - \usepackage[gen]{eurosym}
  - \usepackage[main=french]{babel}
   # We'll use totpages (not lastpage) to get total pages, avoids duplicate-label warnings
  - \usepackage{totpages}
  # Hook AwesomeCV's footer and rewrite its 3rd argument (page text)
  - \makeatletter
  - \let\origmakecvfooter\makecvfooter
  - \renewcommand{\makecvfooter}[3]{\origmakecvfooter{#1}{#2}{\thepage/\ref{TotPages}}}
  - \makeatother
lang: french
date: "\\today"
papersize: letterpaper
---

```{r setup, include = FALSE}
# Make sure to install babel TeX package
# tinytex::tlmgr_install("babel-french")

# Windows French locale for date
try(Sys.setlocale("LC_TIME", "French_France.1252"), silent = TRUE)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#######################
#### SHORT VERSION ####
#######################

# Whether to print a shortened version of the CV
short <- FALSE

########################
#### PACKAGE SETUP #####
########################

# Required packages
library(vitae)
library(dplyr)

# For Google scholar data/visualization
library(scholar)
library(patchwork)
library(see)
library(rsvg)
library(kableExtra)
library(tidyverse)

language <- "FR" # If not EN, will choose the alternative names in the data
# So far only for nice_awards() and nice_grants()

# To format links throughout the CV
source("files/functions.R")

# Automatically bold your name in the publication section
author_bold <- "Thériault, R."

########################
#### GOOGLE SCHOLAR ####
########################

# Specify your Google scholar profile
scholar.profile <- "NrfwEncAAAAJ" # Get it from your Google Scholar profile URL

# Specify your Google scholar short author name
author.name <- "rém thériault"
# Note: correct name may vary (e.g., if you inconsistently used middle name initials)
# Dominique Makowski's was simply "d makowski", so the pattern is unclear 
# But usually it seems 1-3 letters from first name plus full last name

# When in doubt, the correct author name can be obtained through:
# get_scholar_name(scholar.profile) # (after defining 'scholar.profile' above)

# Name inconsistencies should be corrected manually in file 'files/make_data_impact.R' (lines 14-16).

headcolor <- "0a0a0a"

########################
##### INSTRUCTIONS #####
########################

# Change the order of sections below as desired.
# Edit the individual files ("childs") to edit the content as desired.
# Add `eval = !short` to code chunks to make them optional for the short version

# See all instructions and tips here: https://github.com/rempsyc/cv

```

```{r Education parent, child=c('sections/education.Rmd')}
```

```{r Grants parent, child=c('sections/grants.Rmd')}
```

\pagebreak

```{r Awards parent, child=c('sections/awards.Rmd')}
```

```{r Publications parent, child=c('sections/publications.Rmd')}
```

```{r Preprints parent, child=c('sections/preprints.Rmd'), eval = !short}
```

```{r Teaching parent, child=c('sections/teaching.Rmd')}
```

\pagebreak

```{r Invited talks parent, child=c('sections/invited_talks.Rmd'), eval = !short}
```

```{r Conference talks parent, child=c('sections/conference_talks.Rmd'), eval = !short}
```

```{r Conference posters parent, child=c('sections/conference_posters.Rmd'), eval = !short}
```

```{r Software parent, child=c('sections/fr/software.Rmd')}
```

```{r Academic service parent, child=c('sections/service.Rmd'), eval = !short}
```

```{r Media coverage parent, child=c('sections/fr/media_coverage.Rmd'), eval = !short}
```

```{r Blogs parent, child=c('sections/fr/blogs.Rmd'), eval = TRUE}
```

```{r Other experience parent, child=c('sections/fr/other_experience.Rmd'), eval = TRUE}
```

```{r References parent, child=c('sections/references.Rmd'), eval = !short}
```

```{r credit parent, child=c('sections/credit.Rmd'), eval = TRUE}
```

<!-- We skip the sections below for now. They are on the website and it was recommended to avoid them for the CV for applying to prof positions -->


