---
output: html_document
---

\scriptsize
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}

```{r, results='asis'}
nice_header("Media Coverage", "Couverture médiatique", language)
```

\footnotesize

```{r media_en, results='asis', eval=English}
media <- c(
  "**Thériault, R.** (2023, August 28). Pour une positivité responsable et bienveillante [Opinion letter]. *Le Devoir*. Retrieved from: <https://www.ledevoir.com/opinion/idees/796952/serie-l-ete-c-est-fait-pour-penser-pour-une-positivite-responsable-et-bienveillante>",

  "Serafin, P. (2023, May 03). CHOQ.ca rencontre les Lauréat.es du Prix du mérite 2023. *Radio CHOQ.ca*. Retrieved from: https://www.choq.ca/reportages/choq-ca-rencontre-les-laureat-es-du-prix-du-merite-2023.",

  "Jewell, L. (2022, June 23). Member Spotlight: Rémi Thériault. Interview organized by the *Canadian Positive Psychology Association* and conducted by the CPPA President, Louisa Jewell. Retrieved from: https://youtu.be/3H38-k-L7W0.",

  'Paré, C. (2022, June). Page Jeune chercheur étoile : Rémi Thériault ("La réalité virtuelle au service de l\'empathie"). *Magazine Curium*, *55*. <https://curiummag.com/magazine/juin-2022-reinventer-le-voyage/>',

  "Néron, M. (2022, May 7). Êtes-vous courtois dans la rue? [Guest expert]. *Ici Radio-Canada*. Retrieved from: <https://ici.radio-canada.ca/ohdio/premiere/emissions/genre-humain/episodes/625907/rattrapage-du-samedi-7-mai-2022>",

  "Perreault, É. & Néron, M. (2022, March 24). Marie Gendron : Altruisme extrême : donner son rein à un inconnu... de son vivant [Guest expert]. *L'avenir nous appartient*. Télé-Québec. Retrieved from: <https://lavenirnousappartient.telequebec.tv/emissions/333127/lavenir-appartient-a-michel-jean-et-a-la-reconciliation/65381/marie-gendron-altruisme-extreme-donner-son-rein-a-un-inconnu-de-son-vivant>",

  "Handfield, C. (2021, December 19). Adieu solidarité, rebonjour individualisme [Guest expert]. *La Presse*. Retrieved from: <https://www.lapresse.ca/societe/2021-12-19/adieu-solidarite-rebonjour-individualisme.php>",

  "Guillemette, M. (2021, September 1). Dans la peau d'une personne noire: La réalité virtuelle peut-elle réduire les préjugés raciaux? [Featured research] *Québec Science*. Retrieved from: <https://www.quebecscience.qc.ca/societe/personne-noire-realite-virtuelle/>",

  "Morin, I. (2020, May 29). Un peu de courtoisie [Guest expert]. *La Presse*. Retrieved from: <https://www.lapresse.ca/societe/2020-05-29/un-peu-de-courtoisie>",

  "Morin, I. (2020, May 29). Vivre ensemble au temps de la COVID-19 [Guest expert]. *La Presse*. Retrieved from: <https://www.lapresse.ca/societe/2020-05-29/vivre-ensemble-au-temps-de-la-covid-19>",

  "Bourderon, C. and Laliberté, J.-S. (Producers), & Robitaille, É. (Host). (2018, December 7). Avez-vous des limites? *On est tous des humains* [Broadcast interview -- panel guest]. Retrieved from: <https://canalm.vuesetvoix.com/avez-vous-des-limites/>",

  "Bourderon, C. and Bolduc, M. (Producers), & Robitaille, É. (Host). (2018, October 19). Êtes-vous altruiste? *On est tous des humains* [Broadcast interview -- panel guest]. Retrieved from: <https://canalm.vuesetvoix.com/etes-vous-altruiste/>",

  "LaRoche, G. (Producer and host). (2018, August 21). Episode 10 - Student conversation ft. Rémi. *The Happiness Legacy Podcast* [Audio podcast guest]. Retrieved from: <https://thehappinesslegacy.com/podcast>"
)
number_pubs(media, number = count_everything)
```

```{r media_fr, results='asis', eval=French}
media <- c(
  "**Thériault, R.** (28 aout 2023). Pour une positivité responsable et bienveillante [Lettre d'opinion]. *Le Devoir*. https://www.ledevoir.com/opinion/idees/796952/serie-l-ete-c-est-fait-pour-penser-pour-une-positivite-responsable-et-bienveillante",

  "Serafin, P. (3 mai 2023). CHOQ.ca rencontre les Lauréat.es du Prix du mérite 2023. *Radio CHOQ.ca*. https://www.choq.ca/reportages/choq-ca-rencontre-les-laureat-es-du-prix-du-merite-2023",

  "Jewell, L. (23 juin 2022). Member Spotlight: Rémi Thériault. Entrevue organisée par la *Canadian Positive Psychology Association* et conduite par la Présidente de la CPPA, Louisa Jewell. https://youtu.be/3H38-k-L7W0",

  "Paré, C. (juin 2022). Page Jeune chercheur étoile : Rémi Thériault (« La réalité virtuelle au service de l'empathie »). *Magazine Curium*, *55*. https://curiummag.com/magazine/juin-2022-reinventer-le-voyage/",

  "Néron, M. (7 mai 2022). Êtes-vous courtois dans la rue? [expert invité]. *Ici Radio-Canada*. https://ici.radio-canada.ca/ohdio/premiere/emissions/genre-humain/episodes/625907/rattrapage-du-samedi-7-mai-2022",

  "Perreault, É. & Néron, M. (24 mars 2022). Marie Gendron : Altruisme extrême : donner son rein à un inconnu... de son vivant [expert invité]. *L'avenir nous appartient*. Télé-Québec. https://lavenirnousappartient.telequebec.tv/emissions/333127/lavenir-appartient-a-michel-jean-et-a-la-reconciliation/65381/marie-gendron-altruisme-extreme-donner-son-rein-a-un-inconnu-de-son-vivant",

  "Handfield, C. (19 décembre 2021). Adieu solidarité, rebonjour individualisme [expert invité]. *La Presse*. https://www.lapresse.ca/societe/2021-12-19/adieu-solidarite-rebonjour-individualisme.php",

  "Guillemette, M. (1er septembre 2021). Dans la peau d'une personne noire : La réalité virtuelle peut-elle réduire les préjugés raciaux? [Recherche en vedette] *Québec Science*. https://www.quebecscience.qc.ca/societe/personne-noire-realite-virtuelle/",

  "Morin, I. (29 mai 2020). Un peu de courtoisie [expert invité]. *La Presse*. https://www.lapresse.ca/societe/2020-05-29/un-peu-de-courtoisie",

  "Morin, I. (29 mai 2020). Vivre ensemble au temps de la COVID-19 [expert invité]. *La Presse*. https://www.lapresse.ca/societe/2020-05-29/vivre-ensemble-au-temps-de-la-covid-19",

  "Bourderon, C. and Laliberté, J.-S. (Productrices), & Robitaille, É. (Hôte). (7 décembre 2018). Avez-vous des limites? *On est tous des humains* [Entrevue radio – invité du panel]. https://canalm.vuesetvoix.com/avez-vous-des-limites/",

  "Bourderon, C. and Bolduc, M. (Productrices), & Robitaille, É. (Hôte). (19 octobre 2018). Êtes-vous altruiste? *On est tous des humains* [Entrevue radio – invité du panel]. https://canalm.vuesetvoix.com/etes-vous-altruiste/",

  "LaRoche, G. (Productrice et hôte). (21 aout 2018). Episode 10 - Student conversation ft. Rémi. *The Happiness Legacy Podcast* [Invité de balado audio]. https://thehappinesslegacy.com/podcast",

  "Guy, L.-P. (Producteur et hôte). (1er février 2012). Échange sur la relève en économie sociale et l'action communautaire [Entrevue radio – invité du panel]. *FM 103,3 -- La radio allumée*."
)
number_pubs(media, number = count_everything)
```
