---
output: html_document
---

\scriptsize
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}

# Preprints

**Thériault, R.**, Masson, R., & Dandeneau, S. (2025). Is the Mind More Powerful Than the Heart? A Randomized Controlled Trial of Two Loving-Kindness Interventions. https://doi.org/10.31234/osf.io/x4p9v_v2

Brodeur, A., Valenta, D., Marcoci, A., ... **Thériault, R.**, et al. (2025). *Comparing Human-Only, AI-Assisted, and AI-Led Teams on Assessing Research Reproducibility in Quantitative Social Science*. https://econpapers.repec.org/RePEc:zbw:i4rdps:195

Heyman, T., Pronizius, E., Lewis, S. C., ... **Thériault, R.**, et al. (2024). *Crowdsourcing Multiverse Analyses to Explore the Impact of Different Data-processing and Analysis Decisions: A Tutorial*. https://osf.io/fjhv5

Buchanan, E. M., Cuccolo, K. M., Coles, N., ... **Thériault, R.**, et al. (2024). *Measuring the Semantic Priming Effect Across Many Languages*. https://doi.org/10.31219/osf.io/q4fjy

Brodeur, A., Mikola, D., Cook, N., ... **Thériault, R.**, et al. (2024). *Mass Reproducibility and Replicability: A New Hope*. https://econpapers.repec.org/RePEc:zbw:i4rdps:107

<!-- Makowski, D., Patil, I., Ben-Shachar, M. S., Wiernik, B. M., Bacher, E., Lüdecke, D., & **Thériault**, R. (2023). report: Automated reporting of results and statistical models in R. <https://remi-theriault.com/preprints/makowski_et_al_2023.pdf> -->