---
output: html_document
---

\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\footnotesize

# Présentations orales

**Thériault, R.**, Dion-Cliche, F., & Dandeneau, S. (18 juin 2022). Fear of negative evaluation moderates the effect of social inclusion and social feedback on fundamental needs. Présentation orale pour le *2022 Canadian Psychological Association Annual National Convention* à Calgary, AB.

**Thériault, R.**, Masson, R., Archambault, M., & Dandeneau, S. (9 juin 2022). La méditation d’amour-bienveillant augmente-t-elle les comportements de don? Présentation orale pour le donnée au *22e congrès de L’Association scientifique pour la modification du comportement : Bienveillance et résilience : les visages de l’adaptation* à Montréal, QC (congrès virtuelle à cause du COVID).

**Thériault, R.**, Masson, R., Archambault, M., & Dandeneau, S. (16-20 juin 2022). Does loving-kindness meditation increase giving behaviors? Présentation orale pour le *Tenth SELF International Conference* à Québec, QC (congrès virtuel à cause du COVID).

**Thériault, R.** (3 juin 2019). Réduire les préjugés et augmenter l'empathie via la réalité virtuelle. Présentation orale pour le *2019 Congress of the Humanities and Social Sciences* à Vancouver, BC.

**Thériault, R.**, Corber, L., MacLean, C. W., Napoleon, J.-S., Olson, J. A., & Raz, A. (24 aout 2018). Can suggestion affect pulmonary function in children with suspected asthma? Présentation orale pour le *21^st^* *World Congress of Medical and Clinical Hypnosis* à Montréal, QC.

<!-- Dennie, A., Djehounke, L., Light, E., Chamberlain, C. W., **Thériault, R.**, Krol, S., Olson, J., & Raz, A. (2018, June 5). Walking a mile in another's shoes: Can virtual reality decrease prejudice? Conference talk presented by first author at the *Research Day of the Douglas Hospital Research Centre and McGill Department of Psychiatry* in Montréal, QC. -->

**Thériault, R.**, Krol, S., & Raz, A. (14 juillet 2017). Investigating the effects of mental versus embodied perspective-taking on prejudice. Présentation orale pour le *5^th^ World Congress on Positive Psychology* à Montréal, QC.

**Thériault, R.**, Landry, M., Mattuck, S., & Raz, A. (2 juin 2017). The Rubber Hand Illusion: Does load affect EEG & electrodermal activity? Présentation orale pour le *Research Day of the Douglas Hospital Research Centre and McGill Department of Psychiatry* à Montréal, QC.

<!-- Lifshitz, M., Sheiner, E., Olson, J., **Thériault, R**., & Raz, A. (2016, October 6). On suggestibility and placebo. Conference talk presented by first author at the *67^th^ meeting of the Society for Clinical and Experimental Hypnosis* in Boston, MA. -->